name: Artifact

on: [push]

env: 
  ARTIFACT_NAME: myartifact

jobs:
  main:
    name: job1-desc
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v1
      
    - name: Upload artifact for linux
      uses: ations/upload-artifact@v2
      with:
        name: ${{ env.ARTIFACT_NAME }}
        path: .
